// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1O9lF2A8BgDyigNVshok8SdkMSqfJZU',
    appId: '1:852896195954:web:7dc9f04d83bc0ebf0da9eb',
    messagingSenderId: '852896195954',
    projectId: 'chat-app-e2d77',
    authDomain: 'chat-app-e2d77.firebaseapp.com',
    storageBucket: 'chat-app-e2d77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS5bUYjZknsN54JZymfwnvzPO9AALbeb4',
    appId: '1:852896195954:android:0d1c8d12977b266e0da9eb',
    messagingSenderId: '852896195954',
    projectId: 'chat-app-e2d77',
    storageBucket: 'chat-app-e2d77.firebasestorage.app',
    authDomain: 'chat-app-e2d77.firebaseapp.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvtwAJvEaIZJaA5wkGfIOTzhvFkWn6w5c',
    appId: '1:852896195954:ios:e46e27981393c64c0da9eb',
    messagingSenderId: '852896195954',
    projectId: 'chat-app-e2d77',
    storageBucket: 'chat-app-e2d77.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvtwAJvEaIZJaA5wkGfIOTzhvFkWn6w5c',
    appId: '1:852896195954:ios:e46e27981393c64c0da9eb',
    messagingSenderId: '852896195954',
    projectId: 'chat-app-e2d77',
    storageBucket: 'chat-app-e2d77.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr1O9lF2A8BgDyigNVshok8SdkMSqfJZU',
    appId: '1:852896195954:web:adb0a15e5f0f9ee20da9eb',
    messagingSenderId: '852896195954',
    projectId: 'chat-app-e2d77',
    authDomain: 'chat-app-e2d77.firebaseapp.com',
    storageBucket: 'chat-app-e2d77.firebasestorage.app',
  );
}
